Feature startsWith()
Mr-Squirrel/learn-lodash pull request #15
Opened 2023-06-21 09:23 UTC by Meowmir

## Describe your changes
Created a function that returns true if the original string starts with the target, or at the target index.

## Code Usage examples
```js
const string = "abc"
startsWith(string, "a")
//console.log(true)

startsWith(string, "b", 1)
//console.log(true)
```

## Checklist before requesting a review
- [ ] I have added JsDoc comments to all public methods created
- [ ] EsLint is passing for this PR
- [ ] Tests are passing for this PR
- [ ] CI build is passing for this PR
- [ ] I have performed a self-review of my code
- [ ] I have had another developer review my code

2023-06-30 08:39 UTC, Mr-Squirrel requested changes

2023-06-30 08:39 UTC, Mr-Squirrel commented on startsWith.js
> +  return inspectString.charAt(0) === targetString || inspectString.charAt(targetIndex) === targetString
you're comparing characters to full strings.  Please use String.startsWith

2023-08-18 10:39 UTC, Meowmir commented
I've done some changes, but the targetString is only one character, at least in the tests. But I do remember us having this conversation before the vacation..

2023-09-08 07:37 UTC, Mr-Squirrel approved these changes

2023-09-11 11:04 UTC, merged