passing all tests, but feels like it shouldnt
Mr-Squirrel/learn-lodash pull request #23
Opened 2023-08-30 08:59 UTC by Meowmir

## Describe your changes
Created a function to check if value is a function.

## Code Usage examples
```js
console.log(isFunction( () => {} ))
// true

console.log(isFunction(1))
// false
```

## Checklist before requesting a review
- [ ] I have added JsDoc comments to all public methods created
- [ ] EsLint is passing for this PR
- [ ] Tests are passing for this PR
- [ ] CI build is passing for this PR
- [ ] I have performed a self-review of my code
- [ ] I have had another developer review my code

2023-08-30 09:55 UTC, Mr-Squirrel commented on test/utils.js
> +/** Used to detect when a function becomes hot. */
why is this file in this PR?

2023-08-30 09:56 UTC, Mr-Squirrel requested changes
remote unnecessary file

2023-09-11 11:27 UTC, Meowmir commented
how do i remove file from pr?

2023-09-20 09:02 UTC, Mr-Squirrel approved these changes

2023-09-20 09:09 UTC, merged